import type { TradeIdea } from '@jb/contracts';
import { useState, type JSX } from 'react';
import { Link, useParams } from 'react-router-dom';
import { PageHeader } from '@/components/PageHeader';
import { Pill } from '@/components/Pill';
import { fmtUsdCompact } from '@/lib/format';
import { DecisionButtons } from './DecisionButtons';
import { useCombinedRisk } from './riskApi';
import { SuitabilityBadge } from './SuitabilityBadge';

/** Trade ideas generated from signals, holdings and the rubric, with the suitability gate visible. */
export function TradeIdeasPage(): JSX.Element {
  const { clientId = '' } = useParams();
  const q = useCombinedRisk(clientId);
  const [showBlocked, setShowBlocked] = useState(true);
  const d = q.data;
  const ideas = (d?.tradeIdeas ?? []).filter(
    (i) => showBlocked || i.suitability.status !== 'blocked',
  );
  return (
    <div className="max-w-[1400px]">
      <PageHeader
        eyebrow="Customer view · L2"
        title={
          <>
            Trade ideas
            {d && (
              <>
                <span className="mx-2 text-line-2">—</span>
                <Link
                  to={`/clients/${clientId}`}
                  className="text-ink no-underline hover:text-accent"
                >
                  {d.clientName}
                </Link>
              </>
            )}
          </>
        }
        right={
          <>
            <label className="flex items-center gap-1.5 text-[12.5px] text-muted">
              <input
                type="checkbox"
                checked={showBlocked}
                onChange={(e) => {
                  setShowBlocked(e.target.checked);
                }}
                className="accent-[#1f4e79]"
              />
              show blocked
            </label>
            <Link
              to={`/clients/${clientId}/actions`}
              className="rounded border border-line bg-surface px-3 py-1.5 text-[12.5px] text-ink-2 no-underline hover:bg-surface-2"
            >
              Combined risk →
            </Link>
          </>
        }
      >
        <p className="mb-0 mt-1 max-w-3xl text-[12.5px] text-muted">
          Ideas are generated by rules from mandate bands, look-through exposure, liquidity needs,
          the rubric and recent rate signals. Each passes a suitability gate; ideas that fail stay
          visible with the rule that blocked them. Approval here records a decision for the desk, it
          does not place an order.
        </p>
      </PageHeader>
      {q.isPending && <p className="text-muted">Generating…</p>}
      {q.isError && (
        <div className="rounded border border-crit/30 bg-crit-soft px-4 py-3 text-crit">
          {q.error.message}
        </div>
      )}
      {d && ideas.length === 0 && (
        <div className="rounded-md border border-dashed border-line-2 px-4 py-10 text-center text-muted">
          No trade ideas: the portfolios sit inside their bands and limits at this clock.
        </div>
      )}
      <div className="space-y-3">
        {ideas.map((i) => (
          <IdeaCard key={i.id} i={i} clientId={clientId} />
        ))}
      </div>
    </div>
  );
}

function IdeaCard({ i, clientId }: { i: TradeIdea; clientId: string }): JSX.Element {
  const dirTone =
    i.direction === 'buy'
      ? 'ok'
      : i.direction === 'sell'
        ? 'crit'
        : i.direction === 'switch'
          ? 'info'
          : 'neutral';
  return (
    <section
      className={`rounded-md border bg-surface ${i.suitability.status === 'blocked' ? 'border-crit/40' : 'border-line'}`}
    >
      <header className="flex flex-wrap items-center justify-between gap-2 border-b border-line px-4 py-2">
        <div className="flex flex-wrap items-center gap-2">
          <Pill tone={dirTone}>{i.direction.toUpperCase()}</Pill>
          <span className="text-[14px] font-semibold text-ink">{i.title}</span>
          <SuitabilityBadge s={i.suitability} />
        </div>
        <div className="flex items-center gap-2 text-[12px] text-muted" title={i.confidenceNote}>
          confidence{' '}
          <span className="tnum font-mono text-ink">{Math.round(i.confidence * 100)}%</span>
        </div>
      </header>
      <div className="grid grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)_170px] gap-4 px-4 py-3 text-[12.5px]">
        <div>
          <p className="m-0 text-ink-2">{i.rationale}</p>
          <div className="mt-2 font-mono text-[10.5px] text-muted">
            {i.motivatedBy.facts.join(' · ')}
            {i.motivatedBy.signalIds.length > 0 &&
              ` · signals ${i.motivatedBy.signalIds.join(', ')}`}
          </div>
          <div className="mt-1 text-[11px] text-muted">{i.confidenceNote}</div>
        </div>
        <div className="space-y-1">
          {i.sell && (
            <div className="rounded bg-crit-soft/60 px-2 py-1">
              <span className="text-[10.5px] font-semibold uppercase tracking-[0.08em] text-crit">
                Sell
              </span>{' '}
              <span className="text-ink">{i.sell.name}</span>{' '}
              <span className="tnum font-mono text-[11.5px]">
                {fmtUsdCompact(i.sell.amountUsd)}
              </span>{' '}
              <span className="font-mono text-[10.5px] text-muted">{i.sell.portfolioId}</span>
            </div>
          )}
          {i.buy && (
            <div className="rounded bg-ok-soft/60 px-2 py-1">
              <span className="text-[10.5px] font-semibold uppercase tracking-[0.08em] text-ok">
                Buy
              </span>{' '}
              <span className="text-ink">{i.buy.name}</span>{' '}
              <span className="tnum font-mono text-[11.5px]">{fmtUsdCompact(i.buy.amountUsd)}</span>{' '}
              <span className="font-mono text-[10.5px] text-muted">{i.buy.portfolioId}</span>
            </div>
          )}
          {!i.buy && !i.sell && <div className="text-muted">No transaction; hold and monitor.</div>}
          <ul className="m-0 mt-1 list-none space-y-0.5 p-0 text-[11.5px]">
            {i.suitability.checks
              .filter((c) => !c.passed)
              .map((c) => (
                <li key={c.rule} className="text-crit">
                  ✗ {c.rule}: {c.detail}
                </li>
              ))}
          </ul>
        </div>
        <DecisionButtons
          clientId={clientId}
          id={i.id}
          entityType="trade_idea"
          decision={i.decision}
          blocked={i.suitability.status === 'blocked'}
          approveLabel="Approve for desk"
        />
      </div>
    </section>
  );
}
